### ISSUE TITLE
Replace json config files

### ISSUE THREAD

**Issue by theascone** [theascone/dckrmgr#3]
json is quite verbose and unintuitive to hand-code, therefore it would be best to use a different config file standard

**Comment by theascone** [comment]
yaml seems to be a hot candidate

**Comment by Craeckie** [comment]
ya, good point!
Looks good (I'm coming from the XML-World :p)

``` XML
<!-- XML -->
<Director name="Spielberg">
    <Movies>
        <Movie title="Jaws" year="1975"/>
        <Movie title="E.T." year="1982"/>
    </Movies>
</Director>
```

``` YAML
# YAML
Director: 
    name: Spielberg
    Movies:
      - Movie: {title: E.T., year: 1975}
      - Movie: {title: Jaws, year: 1982}
```
